# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/chat.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "chat.RegisterUserRequest" do
    optional :user_name, :string, 1
  end
  add_message "chat.RegisterUserResponse" do
    optional :status, :enum, 1, "chat.ResponseStatus"
    optional :session_id, :string, 2
  end
  add_message "chat.ListUsersRequest" do
    optional :query, :string, 1
  end
  add_message "chat.ListUsersResponse" do
    optional :size, :uint32, 1
    repeated :user_names, :string, 2
  end
  add_message "chat.ListenRequest" do
  end
  add_message "chat.ReceiverMessage" do
    optional :uuid, :string, 2
    optional :user_name, :string, 3
    optional :text, :string, 4
    optional :timestamp, :message, 5, "google.protobuf.Timestamp"
  end
  add_message "chat.SenderMessage" do
    optional :uuid, :string, 1
    optional :session_id, :string, 2
    optional :text, :string, 3
  end
  add_message "chat.SenderMessageStatus" do
    optional :uuid, :string, 1
    optional :status, :enum, 2, "chat.ResponseStatus"
  end
  add_enum "chat.ResponseStatus" do
    value :OK, 0
    value :REJECT, 1
    value :ERROR, 3
  end
end

module Chat
  RegisterUserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("chat.RegisterUserRequest").msgclass
  RegisterUserResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("chat.RegisterUserResponse").msgclass
  ListUsersRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("chat.ListUsersRequest").msgclass
  ListUsersResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("chat.ListUsersResponse").msgclass
  ListenRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("chat.ListenRequest").msgclass
  ReceiverMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("chat.ReceiverMessage").msgclass
  SenderMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("chat.SenderMessage").msgclass
  SenderMessageStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("chat.SenderMessageStatus").msgclass
  ResponseStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("chat.ResponseStatus").enummodule
end
