# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protos/chat.proto for package 'chat'

require 'grpc'
require 'protos/chat_pb'

module Chat
  module Room
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chat.Room'

      rpc :RegisterUser, RegisterUserRequest, RegisterUserResponse
      rpc :ListUsers, ListUsersRequest, ListUsersResponse
      rpc :Listen, ListenRequest, stream(ReceiverMessage)
      rpc :Send, stream(SenderMessage), stream(SenderMessageResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
